"""
Analyse data generated by generate.py.
We need to know all possible modifiers and also, keys for things like abiliities.
"""

import json


class WoWsAnalyse:
    def read_json(self, filename: str) -> dict:
        with open(filename, 'r', encoding='utf8') as f:
            json_dict = json.load(f)
        return json_dict


if __name__ == "__main__":
    analyse = WoWsAnalyse()
    json_dict = analyse.read_json('abilities.json')

    abilities_keys = {}
    for key in json_dict:
        abilities = json_dict[key]['abilities']
        for ability_key in abilities:
            current_ability = abilities[ability_key]
            for variable in current_ability:
                abilities_keys[variable] = type(
                    current_ability[variable],
                ).__name__

    abilities_fields = ''
    abilities_fromJson = ''
    abilities_init = ''
    for key in abilities_keys:
        dart_type = abilities_keys[key]
        if dart_type == 'float':
            dart_type = 'double'
        elif dart_type == 'str':
            dart_type = 'String'
        elif dart_type == 'list':
            dart_type = 'List<String>'
        elif dart_type == 'dict':
            dart_type = 'Map<String, double>'
        abilities_fields += '{}? {};\n'.format(dart_type, key)
        abilities_init += 'this.{},\n'.format(key)
        abilities_fromJson += "{}: json['{}'],\n".format(key, key)

    print(abilities_init)
    print(abilities_fields)
    print(abilities_fromJson)
